### ISSUE TITLE
Duplicate identifier errors

### ISSUE THREAD

**Issue by ADringer** [cstefanache/angular2-img-cropper#15]
When using angular2-img-cropper with a project baed on angular2-seed I get the following errors when trying to compile:

> /node_modules/angular2-highcharts/typings/browser/ambient/es6-shim/index.d.ts(8,14): error TS2300: Duplicate identifier 'PropertyKey'.
/node_modules/angular2-highcharts/typings/browser/ambient/es6-shim/index.d.ts(11,5): error TS2300: Duplicate identifier 'done'.
/node_modules/angular2-highcharts/typings/browser/ambient/es6-shim/index.d.ts(12,5): error TS2300: Duplicate identifier 'value'.
/node_modules/angular2-highcharts/typings/browser/ambient/es6-shim/index.d.ts(250,5): error TS2300: Duplicate identifier 'EPSILON'.
/node_modules/angular2-highcharts/typings/browser/ambient/es6-shim/index.d.ts(285,5): error TS2300: Duplicate identifier 'MAX_SAFE_INTEGER'.
[...]

The type definitions for es6-shim are local in my project in the typings folder, but they are also located in `\node_modules\ng2-img-cropper\typings`

According to [this article](http://blog.mgechev.com/2016/03/28/ambient-type-definitions-duplicate-identifier-typescript-fix/)

> Using <reference/> is considered a bad practice.

I've deleted the `<reference />` tag and it compiles fine. Are you able to remove it?

Note that this same issue occurred with [Angular2-highcharts](https://github.com/gevgeny/angular2-highcharts/issues/6) and they removed the <reference> to solve the issue.

**Comment by cstefanache** [comment]
I am on the road at the moment. I will remove it asap and run the tests.

**Comment by cstefanache** [comment]
Fixed with 0.4.2 release

**Comment by cstefanache** [comment]
comment not removed - I will have to do a 0.4.3 release - sorry

**Comment by cstefanache** [comment]
hmmm ... seems that /// comments are a special thing - can you please check with 0.4.2 change to see if everything is ok? Please note that I removed the .ts files from the built package (just like @angular does) and you should switch loading from js files in system.config.js (see plnkr from readme.md)

**Comment by ADringer** [comment]
Hi,

Thanks for responding so quickly, didn't expect that!

Unfortunately I still get an error when trying to compile my typescript:

> node_modules/ng2-img-cropper/src/imageCropper.d.ts(1,1): error TS6053: File 'c:/
Users/BIO276/Source/Repos/administrationportal/node_modules/ng2-img-cropper/typi
ngs/browser.d.ts' not found.

As ImageCropper is still referencing the local typings (although this doesn't exist anymore).

I don't suppose you had a look at the related bug for [Angular2-Highcharts](https://github.com/gevgeny/angular2-highcharts/issues/6)? It got resolved but I'm not sure what the actual fix was.

Thanks

**Comment by cstefanache** [comment]
Done! Not a single <reference> tag exist in the code at the moment.

The solution was to  remove the reference include the typings only at compilation (in order to avoid angular Map & Promise dependencies issue):

tsconfig.json
"files": [
    "typings/browser.d.ts"
  ],

@ADringer can you please do another test run with 0.4.3?

**Comment by ADringer** [comment]
Perfect, that works like a charm! Thanks very much for sorting that out so quickly.

**Comment by cstefanache** [comment]
a lesson learnt for me. I will notice the rest of the users
